apiVersion: v1
kind: ConfigMap
metadata:
  name: mlops-config
  namespace: mlops
data:
  OPENMETEO_BASE_URL: {{ .Values.openMeteoBaseUrl }}
  BLOB_CONTAINER: {{ .Values.blobContainer }}
  WORKER_URL: http://worker:{{ .Values.worker.port }}
