apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: mlops
spec:
  type: LoadBalancer
  selector:
    app: orchestrator
  ports:
    - port: 8080
      targetPort: {{ .Values.orchestrator.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: mlops
spec:
  type: ClusterIP
  selector:
    app: worker
  ports:
    - port: {{ .Values.worker.port }}
      targetPort: {{ .Values.worker.port }}
