apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: mlops
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: mlops-secrets-provider
      containers:
        - name: worker
          image: {{ .Values.worker.image }}
          ports:
            - containerPort: {{ .Values.worker.port }}
          envFrom:
            - configMapRef:
                name: mlops-config
            - secretRef:
                name: mlops-secrets
          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets
              readOnly: true
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
